
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redhatcop-redhat-io-v1alpha1-authenginemount
  failurePolicy: Fail
  name: mauthenginemount.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - authenginemounts
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redhatcop-redhat-io-v1alpha1-databasesecretengineconfig
  failurePolicy: Fail
  name: mdatabasesecretengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - databasesecretengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redhatcop-redhat-io-v1alpha1-databasesecretenginerole
  failurePolicy: Fail
  name: mdatabasesecretenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - databasesecretengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redhatcop-redhat-io-v1alpha1-githubsecretengineconfig
  failurePolicy: Fail
  name: mgithubsecretengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - githubsecretengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redhatcop-redhat-io-v1alpha1-githubsecretenginerole
  failurePolicy: Fail
  name: mgithubsecretenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - githubsecretengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redhatcop-redhat-io-v1alpha1-kubernetesauthengineconfig
  failurePolicy: Fail
  name: mkubernetesauthengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - kubernetesauthengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redhatcop-redhat-io-v1alpha1-kubernetesauthenginerole
  failurePolicy: Fail
  name: mkubernetesauthenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - kubernetesauthengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redhatcop-redhat-io-v1alpha1-passwordpolicy
  failurePolicy: Fail
  name: mpasswordpolicy.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - passwordpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redhatcop-redhat-io-v1alpha1-policy
  failurePolicy: Fail
  name: mpolicy.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - policies
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redhatcop-redhat-io-v1alpha1-rabbitmqsecretengineconfig
  failurePolicy: Fail
  name: mrabbitmqsecretengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rabbitmqsecretengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redhatcop-redhat-io-v1alpha1-rabbitmqsecretenginerole
  failurePolicy: Fail
  name: mrabbitmqsecretenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rabbitmqsecretengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redhatcop-redhat-io-v1alpha1-randomsecret
  failurePolicy: Fail
  name: mrandomsecret.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - randomsecrets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redhatcop-redhat-io-v1alpha1-secretenginemount
  failurePolicy: Fail
  name: msecretenginemount.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - secretenginemounts
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redhatcop-redhat-io-v1alpha1-vaultsecret
  failurePolicy: Fail
  name: mvaultsecret.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vaultsecrets
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-redhatcop-redhat-io-v1alpha1-authenginemount
  failurePolicy: Fail
  name: vauthenginemount.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - authenginemounts
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-redhatcop-redhat-io-v1alpha1-databasesecretengineconfig
  failurePolicy: Fail
  name: vdatabasesecretengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - databasesecretengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-redhatcop-redhat-io-v1alpha1-databasesecretenginerole
  failurePolicy: Fail
  name: vdatabasesecretenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - databasesecretengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-redhatcop-redhat-io-v1alpha1-githubsecretengineconfig
  failurePolicy: Fail
  name: vgithubsecretengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - githubsecretengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-redhatcop-redhat-io-v1alpha1-githubsecretenginerole
  failurePolicy: Fail
  name: vgithubsecretenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - githubsecretengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-redhatcop-redhat-io-v1alpha1-kubernetesauthengineconfig
  failurePolicy: Fail
  name: vkubernetesauthengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - kubernetesauthengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-redhatcop-redhat-io-v1alpha1-kubernetesauthenginerole
  failurePolicy: Fail
  name: vkubernetesauthenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubernetesauthengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-redhatcop-redhat-io-v1alpha1-rabbitmqsecretengineconfig
  failurePolicy: Fail
  name: vrabbitmqsecretengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rabbitmqsecretengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-redhatcop-redhat-io-v1alpha1-rabbitmqsecretenginerole
  failurePolicy: Fail
  name: vrabbitmqsecretenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rabbitmqsecretengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-redhatcop-redhat-io-v1alpha1-randomsecret
  failurePolicy: Fail
  name: vrandomsecret.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - randomsecrets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-redhatcop-redhat-io-v1alpha1-secretenginemount
  failurePolicy: Fail
  name: vsecretenginemount.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - secretenginemounts
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-redhatcop-redhat-io-v1alpha1-vaultsecret
  failurePolicy: Fail
  name: vvaultsecret.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vaultsecrets
  sideEffects: None
