- op: add
  path: /metadata/annotations
  value:
    service.alpha.openshift.io/serving-cert-secret-name: webhook-server-cert
- op: replace
  path: /metadata/name
  value: vault-config-operator-webhook-service    