---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - authenginemounts
  - azureauthengineconfigs
  - azureauthengineroles
  - azuresecretengineconfigs
  - azuresecretengineroles
  - certauthengineconfigs
  - certauthengineroles
  - databasesecretengineconfigs
  - databasesecretengineroles
  - databasesecretenginestaticroles
  - gcpauthengineconfigs
  - gcpauthengineroles
  - githubsecretengineconfigs
  - githubsecretengineroles
  - groupaliases
  - groups
  - jwtoidcauthengineconfigs
  - jwtoidcauthengineroles
  - kubernetesauthengineconfigs
  - kubernetesauthengineroles
  - kubernetessecretengineconfigs
  - kubernetessecretengineroles
  - ldapauthengineconfigs
  - ldapauthenginegroups
  - passwordpolicies
  - pkisecretengineconfigs
  - pkisecretengineroles
  - policies
  - quaysecretengineconfigs
  - quaysecretengineroles
  - quaysecretenginestaticroles
  - rabbitmqsecretengineconfigs
  - rabbitmqsecretengineroles
  - randomsecrets
  - secretenginemounts
  - vaultsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - authenginemounts/finalizers
  - azureauthengineconfigs/finalizers
  - azureauthengineroles/finalizers
  - azuresecretengineconfigs/finalizers
  - azuresecretengineroles/finalizers
  - certauthengineconfigs/finalizers
  - certauthengineroles/finalizers
  - databasesecretengineconfigs/finalizers
  - databasesecretengineroles/finalizers
  - databasesecretenginestaticroles/finalizers
  - gcpauthengineconfigs/finalizers
  - gcpauthengineroles/finalizers
  - githubsecretengineconfigs/finalizers
  - githubsecretengineroles/finalizers
  - groupaliases/finalizers
  - groups/finalizers
  - jwtoidcauthengineconfigs/finalizers
  - jwtoidcauthengineroles/finalizers
  - kubernetesauthengineconfigs/finalizers
  - kubernetesauthengineroles/finalizers
  - kubernetessecretengineconfigs/finalizers
  - kubernetessecretengineroles/finalizers
  - ldapauthengineconfigs/finalizers
  - ldapauthenginegroups/finalizers
  - passwordpolicies/finalizers
  - pkisecretengineconfigs/finalizers
  - pkisecretengineroles/finalizers
  - policies/finalizers
  - quaysecretengineconfigs/finalizers
  - quaysecretengineroles/finalizers
  - quaysecretenginestaticroles/finalizers
  - rabbitmqsecretengineroles/finalizers
  - randomsecrets/finalizers
  - secretenginemounts/finalizers
  - vaultsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - authenginemounts/status
  - azureauthengineconfigs/status
  - azureauthengineroles/status
  - azuresecretengineconfigs/status
  - azuresecretengineroles/status
  - certauthengineconfigs/status
  - certauthengineroles/status
  - databasesecretengineconfigs/status
  - databasesecretengineroles/status
  - databasesecretenginestaticroles/status
  - gcpauthengineconfigs/status
  - gcpauthengineroles/status
  - githubsecretengineconfigs/status
  - githubsecretengineroles/status
  - groupaliases/status
  - groups/status
  - jwtoidcauthengineconfigs/status
  - jwtoidcauthengineroles/status
  - kubernetesauthengineconfigs/status
  - kubernetesauthengineroles/status
  - kubernetessecretengineconfigs/status
  - kubernetessecretengineroles/status
  - ldapauthengineconfigs/status
  - ldapauthenginegroups/status
  - passwordpolicies/status
  - pkisecretengineconfigs/status
  - pkisecretengineroles/status
  - policies/status
  - quaysecretengineconfigs/status
  - quaysecretengineroles/status
  - quaysecretenginestaticroles/status
  - rabbitmqsecretengineconfigs/status
  - rabbitmqsecretengineroles/status
  - randomsecrets/status
  - secretenginemounts/status
  - vaultsecrets/status
  verbs:
  - get
  - patch
  - update
