
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - authenginemounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - authenginemounts/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - authenginemounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretengineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretengineconfigs
  - randomsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretengineconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretengineconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretengineroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretengineroles/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretengineroles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - githubsecretengineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - githubsecretengineconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - githubsecretengineconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - githubsecretengineroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - githubsecretengineroles/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - githubsecretengineroles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - kubernetesauthengineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - kubernetesauthengineconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - kubernetesauthengineconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - kubernetesauthengineroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - kubernetesauthengineroles/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - kubernetesauthengineroles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - passwordpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - passwordpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - passwordpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - policies/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - policies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - randomsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - randomsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - randomsecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - secretenginemounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - secretenginemounts/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - secretenginemounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - vaultsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - vaultsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - vaultsecrets/status
  verbs:
  - get
  - patch
  - update
