apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Full Lifecycle
    categories: Security
    certified: "false"
    containerImage: quay.io/redhat-cop/vault-config-operator
    createdAt: 5/28/2019
    description: This operator provides primitives to declaratively configure Hashicorp
      Vault.
    operatorframework.io/suggested-namespace: vault-config-operator
    operatorframework.io/cluster-monitoring: "true"
    operators.openshift.io/infrastructure-features: '["Disconnected"]'
    repository: https://github.com/redhat-cop/vault-config-operator
    support: Best Effort
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.arm64: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/arch.s390x: supported
    operatorframework.io/os.linux: supported
  name: vault-config-operator.v0.0.0
  namespace: placeholder
spec:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AuthEngineMount is the Schema for the authenginemounts API
      displayName: Auth Engine Mount
      kind: AuthEngineMount
      name: authenginemounts.redhatcop.redhat.io
      version: v1alpha1
    - description: DatabaseSecretEngineConfig is the Schema for the databasesecretengineconfigs
        API
      displayName: Database Secret Engine Config
      kind: DatabaseSecretEngineConfig
      name: databasesecretengineconfigs.redhatcop.redhat.io
      version: v1alpha1
    - description: DatabaseSecretEngineRole is the Schema for the databasesecretengineroles
        API
      displayName: Database Secret Engine Role
      kind: DatabaseSecretEngineRole
      name: databasesecretengineroles.redhatcop.redhat.io
      version: v1alpha1
    - description: GitHubSecretEngineConfig is the Schema for the githubsecretengineconfigs
        API
      displayName: Git Hub Secret Engine Config
      kind: GitHubSecretEngineConfig
      name: githubsecretengineconfigs.redhatcop.redhat.io
      version: v1alpha1
    - description: GitHubSecretEngineRole is the Schema for the githubsecretengineroles
        API
      displayName: Git Hub Secret Engine Role
      kind: GitHubSecretEngineRole
      name: githubsecretengineroles.redhatcop.redhat.io
      version: v1alpha1
    - description: KubernetesAuthEngineConfig is the Schema for the kubernetesauthengineconfigs
        API
      displayName: Kubernetes Auth Engine Config
      kind: KubernetesAuthEngineConfig
      name: kubernetesauthengineconfigs.redhatcop.redhat.io
      version: v1alpha1
    - description: KubernetesAuthEngineRole can be used to define a KubernetesAuthEngineRole
        for the kube-auth authentication method
      displayName: Kubernetes Auth Engine Role
      kind: KubernetesAuthEngineRole
      name: kubernetesauthengineroles.redhatcop.redhat.io
      version: v1alpha1
    - description: PasswordPolicy is the Schema for the passowordpolicies API
      displayName: Password Policy
      kind: PasswordPolicy
      name: passwordpolicies.redhatcop.redhat.io
      version: v1alpha1
    - description: PKISecretEngineConfig is the Schema for the pkisecretengineconfigs
        API
      displayName: PKISecret Engine Config
      kind: PKISecretEngineConfig
      name: pkisecretengineconfigs.redhatcop.redhat.io
      version: v1alpha1
    - description: PKISecretEngineRole is the Schema for the pkisecretengineroles
        API
      displayName: PKISecret Engine Role
      kind: PKISecretEngineRole
      name: pkisecretengineroles.redhatcop.redhat.io
      version: v1alpha1
    - description: Policy is the Schema for the policies API
      displayName: Policy
      kind: Policy
      name: policies.redhatcop.redhat.io
      version: v1alpha1
    - description: RabbitMQSecretEngineConfig is the Schema for the rabbitmqsecretengineconfigs
        API
      displayName: Rabbit MQSecret Engine Config
      kind: RabbitMQSecretEngineConfig
      name: rabbitmqsecretengineconfigs.redhatcop.redhat.io
      version: v1alpha1
    - description: RabbitMQSecretEngineRole is the Schema for the rabbitmqsecretengineroles
        API
      displayName: Rabbit MQSecret Engine Role
      kind: RabbitMQSecretEngineRole
      name: rabbitmqsecretengineroles.redhatcop.redhat.io
      version: v1alpha1
    - description: RandomSecret is the Schema for the randomsecrets API
      displayName: Random Secret
      kind: RandomSecret
      name: randomsecrets.redhatcop.redhat.io
      version: v1alpha1
    - description: SecretEngineMount is the Schema for the secretenginemounts API
      displayName: Secret Engine Mount
      kind: SecretEngineMount
      name: secretenginemounts.redhatcop.redhat.io
      version: v1alpha1
    - description: VaultSecret is the Schema for the vaultsecrets API
      displayName: Vault Secret
      kind: VaultSecret
      name: vaultsecrets.redhatcop.redhat.io
      version: v1alpha1
  description: |
    This operator helps set up Vault Configurations. The main intent is to do so such that subsequently pods can consume the secrets made available.
    There are two main principles through all of the capabilities of this operator:

    1. high-fidelity API. The CRD exposed by this operator reflect field by field the Vault APIs. This is because we don't want to make any assumption on the kinds of configuration workflow that user will set up. That being said the Vault API is very extensive and we are starting with enough API coverage to support, we think, some simple and very common configuration workflows.
    2. attention to security (after all we are integrating with a security tool). To prevent credential leaks we give no permissions to the operator itself against Vault. All APIs exposed by this operator contains enough information to authenticate to Vault using a local service account (local to the namespace where the API exist). In other word for a namespace user to be abel to successfully configure Vault, a service account in that namespace must have been previously given the needed Vault permissions.

    Currently this operator supports the following CRDs:

    1. [Policy](https://github.com/redhat-cop/vault-config-operator#policy) Configures Vault [Policies](https://www.vaultproject.io/docs/concepts/policies)
    2. [KubernetesAuthEngineRole](https://github.com/redhat-cop/vault-config-operator#KubernetesAuthEngineRole) Configures a Vault [Kubernetes Authentication](https://www.vaultproject.io/docs/auth/kubernetes) Role
    3. [SecretEngineMount](https://github.com/redhat-cop/vault-config-operator#SecretEngineMount) Configures a Mount point for a [SecretEngine](https://www.vaultproject.io/docs/secrets)
    4. [DatabaseSecretEngineConfig](https://github.com/redhat-cop/vault-config-operator#DatabaseSecretEngineConfig) Configures a [Database Secret Engine](https://www.vaultproject.io/docs/secrets/databases) Connection
    5. [DatabaseSecretEngineRole](https://github.com/redhat-cop/vault-config-operator#DatabaseSecretEngineRole) Configures a [Database Secret Engine](https://www.vaultproject.io/docs/secrets/databases) Role
    6. [RandomSecret](https://github.com/redhat-cop/vault-config-operator#RandomSecret) Creates a random secret in a vault [kv Secret Engine](https://www.vaultproject.io/docs/secrets/kv) with one password field generated using a [PasswordPolicy](https://www.vaultproject.io/docs/concepts/password-policies)vault-config-operator
  displayName: Vault Config Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAQAAAD2e2DtAAAeeElEQVR42u2debxcRZXHv92vX7+QBAghEVQcIgRBCEmAEEBCEBCIwW2UZcKgYYYlLIEEFXUg6AyggIIQlpHVhS2YoAQIqwoowxbZRIWwBRBFtizkQfJe39td80edW7fu7dv9bnded/p1qs6Hzyf0u327qs6vTp06dRZwzTXXXHPNNddcc80111xzzTXXXHPNNddcc80119bHliFLh6O2oSyZ2pjvWvu1lCDQD41gfw7lEEdtQYeyPyMs7lZFCeT5IctQjtqKlvFDuoTDVVf/YP6AQlGi6KhtqIRC8SCDq0uBLHAVih6KlBy1FRXpQXFlNRmQAbalgKIk/zlqFwo42ssnKsuADuBoFD4lx/42hEAJH8XRwumElgO+g6Lg2N+mECig+I5w2gHAAcABwAHAAcABwAHAASAVAEqiSTpqfVIVOLgWANCv9Z1sGADr3Df86uctQH9awHPUslSwONXPEqCI4g52ZxzjGeeoJWk849idO1HG+t9vACiiWMlwd6k+ANoI3kuUAmsNgBfoJFObb4lrTffjypDnReFYPwPgRbrkznCwo5Ykfc83iJcbC4DdeIM3+IejlqI3eIOJAHQ1GgCT3WGrRWmv5gBgkvMWakmfnxJ7NgcAe1U5azpadw4fygHAAcABwAHAAcABwAHAAcABwAHAAcABwAHAAcABwAFgbQAQOBh5KJ4jL5ZAD98Ej7nJb2MAaAYX8VEolokE2Ff+6rsQsvYHQPCiJVzFLAkp+hd+wC184CDQ7gAI2N/DCXTGEkjAx7nFxRGuHxLgAADydJElS5YOukQW/AIlPqiOBW0pATwUZwGdCTHlncBglib+lKO22QLeZwsJJ/4MVwhdzVmMAPLA6Sg8JwHaEwA+ij/Krr+jnAQC+rXA4oAKQQiO2gQAvxFGT0fRI0EhvSj+zgbiH1h0OsD6AIAjjMavQ0ReZZAAwB0E1wsAfNWKDCyieM0BwAHAbQEOAA4ADgAOAA4ADgAOAI4FDgCOHAAcOQA4cgBw5ADgyAHAkQOAIwcARw4AjhwAHDkAOHIAqHdo8TzlrQq4pH6W2h8AjWRIGJnoySdFCpIHt9SCzC/imYn3xFu6OSBomk+gaqJPYBiWqqlgPJPXbmorVT5Qdb8v2lNfcnbbPR3wADgSRS8+Pj4eitcb7hVcMrnve1nAMUxiDBM4hIv4u+ldWgjY20gRH4+CRDhrsj+pVXwHlRQUiteZyyFMYAyTOJr59DYtfrJhAHhIKk3uFXvZw/L5Pg0SciELFrJtrJ8b8z2KqSAQsrJoRHIa8vAECul+Qffku2wU6+l2LLR6MeAAUETxLsMlNOQkHuURHuFhHmMRYyUyaGZDIoPCiZ8jPeuSoNROyVHwaVai8KowqGSKJXrWp908yx1cwVnM5iimcSiHcjhHMZuzuII7eJbuCBD8quzTf/NQrGBviaDslBDaLpnmM5oCgQaFhvkojhdWh5HBWVNnFBYb8dffw/FRnA1kZEo7GCp6R45OYBdWVIBAyVLJgs9e4jpmsw+bVRq8mYPN2ZuTuY6XLBgUE2WBzf6dgU559yCGyux0kgG+34QQ2gZFB2sZMBroIG8FiOYEEnMaFiDuo/iD6dWmnMOfWcYr3MAEIEsnsHMCBEpGd/DlPf/HaUyU1BYYedJFnhwdQjnydJk1i0zjRE7jIfMePwaCcvZngV2Zx6ss4xl+wHAz1Q82ZJk0QQLobr/GpFiJab0iz7REbX8f/koo9hXZsy1LI38/qgIEQm1cD/55zmRHK5q5K2WpiwxdVj6EHTmTF2Q5eJETRDn7j4r0cynbygj2tUY1oAAQ6re/YiZTRAZsyjT+m782bG/TW8/Twq4unkHRg0+Johywjk2EgF6peuAPcLApb9Flya4R7MERnMbF3Mgi7uNBHuQ+FnEjF/NfHMEejDAwCb85iEO4X0DgmwmPs3+GHFaLlPDpQfEnkZQZnmpwzbUG5wjS//9arF6A3zBDRwHFXKBLVlXBWnWaATMSIBDs+ffyGSPGgzrZo/gql/EoK/ucyPf4I5fxVbY0ki7YPvbjXqMTVGK/b0mIgkirLmCujGqAASBc4wUUL5h6AUXRjxtlAfBQzBLxeb2cM0oWIJOkQA8KxRN8zqxe3bblW/ye1RH9oiCn/pA8CpahSaH4gAc41RxBA1kwlSdQ8mvl7C9Gjp4eiutkFCc3OI9CQ/MEBhHB8TyBjTMA+yiOkR4tighPGwK2FFiGYgWzyQBZEbxdHMZd9Fps9yvY6aP3Db4FhV7u4jAZt1aDM8xmBYplVdgfjmKRjOLogbkFhNTMRJF67XxDhOc1IjyrQ+BT/JKthU0AGzKbJQmn+VIqFTRuQXie2WxovX0rbuJTfbBf9/pKGcU3BrIEUE3PFOrJ1OWBg80WUBkCHWYEGSDHTF6TVe/VeS9nC3JfNKCTyAFZM30dVdgfbAFflFFcLaNyAEg1mPDXMsC9KHoTzuAhBDokfxnAFJ6JrPuoqA8FfTGiAxQTr4TCTUEz7xmmiIaRFdhVYr/u8e0ygqCQm5MAqVefj+IQWT2b8JTZBpIgcCzQQYYMcIGlp4fMD28E/JiqFzc/FSK3ALZVIjhjnA9kyPTB/gKKRxkqI5jW8IyKbZcs2kfxHF2Sjq4vCMwwAnkflkesg+F6t3fgIu/zOn/iIe7nfh7iT7zO+9aUlQwM7A3EQ7GcT5tNpzr7H2Oo9H4ILw5MS+C6A0Aw3deZjIRppIBmS7l1MHTSeJs7OZvD2ZXNGGRNQ45BbMZEDuds7uBNM2avzOq3E9BBB3BsSvbDgoipygEgtTHYR3FZagjMSLQOhnr8BRzAsMh4s3SQIyeyw75uPpALrDNEktUvPfuv6ePW0gGgD3eQ+iHQIyabeRxo7jNzEcNwvGXJm8nJcwA3sibR7FMr+weoP8C6BIANgZ8YCAzjydQQWI6im7lsU2YWzjCM8RzEdGbyDb7OTKZzEOMZZl10BXbEbZhLN4rlLc3+Nq0YEnra1QOBPbia0fK9TpPh/CguZzErElQynxUs5kqOkm+F39uaq9ijpdnftiVjkiHwRAoIdJi1rP+1JbN5UAR6aKr1hKJG2h4e5OtyGdRhval12d/GNYOSILBxKgiEpqFd+DmrIjcCxUSv4KiVYBXXMsEy+7Qy+9u6aFQcArmUEOiQHf2i1DcCSbcAc0VrSHvwy60T9rd51bBQHbyqRghkgX1ZaT1ZSnkE1d9YwT5mQ0nDfr1d/Lzp7G/7snHBSfwZ6Xquho0g2Xewr2ug0OyT3uqnZU4HTzbB8LOeSYBAOO9iVll6CHTWBIFS3WafnPGVHmf5BTkA9OP6v0AmOGepg4/3KwRKVXz90qh+XdK785ouA9pcCSyi+AfDpI8/4ucNgUBpLY2+NzFXergRfzPfcQDohw3AQ3GiXK2Ox0dxab9DYG3Zf7XZpPLAcZYnowNAv1wN5yUm6S6xzV/WrxAo9cOVT48E02aATv7a8Cvg9cQQpNf/sbLDHiSeNX7MNFQfBEoUrXhgb62vfHwUX5CeHt1UGdDGEqCIYilDZGU9ZHzv/ZhpqDoEjim7KYxLgJ66Nf/Q7OOjeER6OpiXmlhTsW3vAvT6nyOr6nOWa5WGwOXm8LUxf6wJAopeulnGMrrFdbxWzV8fSH8WSVhhy4DTmygD2hgAivf5uEz33ZEd3JP8BRjde3FVCBxtnpzI2Uzlk2zKUIYygu05iLPZ1UxN+tUPvy/r0z3S21F0D+wUMa2wBXgoFkjfdrYs+cG+vUfENLRhFQgUUXzT2PWTm7blnWqeT2P2mRgxVennd5EnFjTYGbzt/QGi3sE/tiIE9NbwKzkZDDbq4EZlG0HJAEnxI8PoQbFJyDHIAOM86xuliqpfhqHy6zeX9etC6fEhTauv3qYAKKJ4k00AGMwrZljBipskE30+11sQWBy7/NFMeZZdzeVu4PQ1nFGMYrhxGAn+NoFnIzt7kuY/37B5r4jht4jiFYHkJrzZ4HiANt8CPBQ3ypRPlakM8xfdLyvwIyxH8b+JEAjYv4jBQE5W+dbM4maeZxWrWcMqlrCAWRJa1kEOGMyiyJ1ektlnOR+VHjxgzvxBHOVB8uSNTdoE2lQC+FaA9aVl2vZ0+cscMcKEdoFQF9DT/0srrm888yKxwiGtYR7jrCfnG+YlnfvXWKeT/4ycTjyxVAbB7b6TAPWfAHrFqTPHc0aY6jX2FptK8oYXJQowOBTaEAi08oB135eJ8SKhH0WTirLI2dbTv0HhVTD7+FbA/EjeifXuOZnkT8SC2hwAatQAnhGhPS6SFM5Dca0w5PNma0iCgOIVhhl74X3G078UURPtiH7Fb9lIvjGcV1EVrH66f1PLRH2QxmKsbCh/booW0JZbgIfipyKQZ1iiVG8Ah8tfbEOMh+IKCwKPodhHntuQx1H0VnQKs1NhLGaIfGs/E+NX7uvniY9SHphe1r9jI/1zW0CdWQJmy156udnTNaO62ULOBq9ZymHJBJZrhm3BySat1R0Ssauq+gMoeepWkxDrFLZIZL+WAC9L6rpRrLaAVRCNpAs4pcGZAdpcB5gievZDVk4i38pUOjly3LPXJVYcvzbuFFJ46YTZfU42JqZkV8/gTbtLtPATsR4+KD38rNMB6h9SD1tJvo93rJ20gOJiWV+nRtZXHAKBO/eWrErtoBGYjpfxYSBjbAPlnr76l04WUX+lpQVoJXUoAKPpcZFB9d4C/lMMKttbSWL0tM+Qab8htsPGIaANvxfE0sz0PZkFFGdazuXJjt4eimukJ7MtKOo3bAfAEN5qwq1gGwLAR/E4WTLAgWU6+36yOh8vO2eHELhIhPAw3ogYkdJsPnp/30DecEki+6Oi/qCyPu4vAHyyCa4hbQqAO6VXUR1b0SPxexuxLOGQFdzK3SLKW+0WefuQlxMFstzJsyS+ijpx/ljrCQ2NI+TbdzsA1HsIvEHEq61JF1Esl8TsW1fYX/VQv2XZEAs1J4kqyKXOIOC0Cm8oofiADwPwId6PbVOzBIDzmnAQbFMAXC4s/F4sif1S6cnuFeJv9Nr8N9Hj76vDHFsytw3ReilJ2sJYOZC+ZV1WFVCcIb2/ygGgHrLTxZ5jJVotovizJITbt6pRZ3+x6y+pwxZXigBtSsXfUZTYXaZ9qTXtBRTfl95f0uA0sW0MgAtkCn8Uq2PylGjn1Rij2AuADYyPfu2nkHcYAsDeFUasP5ksQHs+JgHOk95f6ABQLwAulCk8LwaApwUAB1QFQFDD44W6JUBwDN236u8E0/5iTAKc06RE0W0MgOBS9azYFrBELmwnV1yZJRSfL7Mi1n4Vpbeaf60AIX3tM0EkzesxCfA/0vufOB2gXiXwZ3IKiFcyClbm2ArmnTCWIA9cWxcDPBQ3ix5/YgV7vj6Sbi25xVZap4DgFFL/7zsAoPi1MGBGzA7wAZsDsBkfJPQksOb/WFbgrJrds4Or4VNjziilhGlfycaSQHpNzA4Q5Du/1QGgXkNQYGX7siWCbbHblZCDN8zU+zv59o415+kLXLx3kDf8oczXONwm/iLTuVfEibSI4kuRLcgBoA4t/CXZ6+3ylHpyD5ET+j2xybWTuk40Fc5+V1O4dvCGO8XcDLtViCn0UCyUmftaTEoVxQk1ejx0AKhpSN2MFFH/fmx/DYws5yeUuLGze+jLoC8aY3DaFDFFcSXJCgR2SaxQFpz2BwE/iJXb6uZDZX13AKhxSEUxstgegVH1bFrEHTNc/TsZJw59m3dPohCvJPwLkqc4a8pVlkcWBzD5ilXZxL4O/qtM8x4uUeTa+AR/Tab/5tj0viZXMFuKGmhH+C5jvGH/SNkqRrMqRbHZ8B2vMlw2kM0qQEA/u4qPisfCP2MQnS/fOrIpfsFtCYACih+KqD8jJmAVnxIG/d6qy6nZP86EeM7iZTa0nEfTZAgpoFjNLibG4FVOrlCkzhdFs0NshaXIJjUncZNyAKjxHBBULz+wLNLnu2U+QXH26wjfy02+z8PEwFSqUm62gKKbyUCOLHAFCsVxFTORn2KZqqKRRAdIz3/XlEQRbesWrotXw6a8a4lYH8Vi2d9Hy/nbQ/FuGfs9CS3RMUGTpZZQIVYbvGQVpfwLOwA5chLwoTee8hQTJRSr2Uo8Ap+0YoPsfg9P9FhwAKjhNH6g9Oy2mOe9MuHcv5I4nXcZWxbfr6dhqmHpMOZKxuASHgXJFVww/sA/YpB5dooVV5ycjP5X0oPdI9GBHorb5C9TmhQg3qYAKKA4V4TsiZGQDk8cQ/NyJRRl/3Gmz3pd+nzRqkO+DefxStmv/Z2LxYtP1/z+HAWzqpMhoMV8PuYyFqa06gLObYoG0LbBoT6KJ+UotpXR94P+vM1IUQQfZg07GPYfb56wi82eYqqE6Kubffg2V7CABVzFaRwodQEDJ9CTze8n5xoaj8ej8usjeTsStxxsDUS2BgeAOrcAZfKD3lG2zk6VFTiZ3YzaFmV/tAD2JyMgKE8PkZVis/Mj7C+HQA7Yy1Q3P7VMNt0hPd4lMg4HgDqjgwLPmmjxtSKKv7GhCd/oSFz9oZq3Roy7gWkoS54u8kJZ6y93oliTED1YXo8gCwyV2CRlxS0fLj3+flOiglQ7p4gponhefneIWNVL1qn/TGOuzQInlLHfPt0/xDADl5Flox9poog24eFUaai1kfiMyPrX6SGGRJzRlAPA2mwCvtyrBZkAvAhTn5OCzn2z/9FIYrfV/J6fci5zmMM5XMMDrOFqK9fQY6lKVUIHz0eetC0UX6wpGsEBoIpfwJ2yNje3rAEeircZbxK7pGF/GOKZTFfHIosrQ+A4s+lMtEpVapf1j0hvFzUtRVSbZwotoZgoCtfZwhYPxTuMMWyojf0eRXw8CkIevpSGrQ0CWVH1Autg4AmYByY0NWV826eKvUn6tylvirvH24wxB79a2R+1AaqIBl8rBLRdYKXp1Ujp6Q0uVWz/HgYnyMqaieoX9if7+NcPAW0ami293LmuovUOAFX8c243/j1P8T6f7Gf21wsB2zTUyzPmJLGwySUj2r5kTBHF52R17coEY/bpP/avHQRywJ7sKT2c0kT9f70AgLbKPUsuZvY5sV/Zv3YQ6DCrP8szlo+CA0A/bgM/NDk7+mZ/vXX84hDIpYZAlgwZOam4qmH9rgYWjCOYNvvMTM3+K2qs4xdC4PKaIKBNQzoWsdBUFXA9OAXoc39o9jkpBfs1Qy5HUTQuIOmSRJXkGzrXl/YsTgeBLDDBMg05JbAf2b+jmeKTUq1+fbUzkeskPVyRguUcbjPHTkHvC+sVvVzPbnJJlKtJF6itVKUDQCr2h+f+k1IL/6y54D2Xl6yxaNufT1HIF7tgOGkvc665PM7WqAt0rgMINBQAwTEsDoBSy7K/E8ixvejxOZmWKVzI0/RU/c0enmYunxWn85ycIbYjl/JEcGzMOugNdH8A21s2uJadhG9qcZdalP1a87+UUXI4y5uKAKP4MqdzDXfxOEt4lVdZwh+5i2s4ja+wlakm0CUHu1FcUtOhMITALk2EQIMAUIq4Rb4hANjbOGw1LualP9ivUHRzGWNkfJ3SfwwY8gxikHEHwbA+KCAxhkvprvmmcMY6gEBDAGC7U/2W0zlYJmozZnChydHbGAgEv/x23ez35H5P4bOIaeKmHZSHyRvvvyCdZD5SRmY407hdvu/VfFMYh0DjjUINAoDu+ltMtZ4Kpm0oF1lbRCPiAhXLLPafXIfZR5kU8Iq3uIlj2N5sBsktz/Ycw428ZbwR7PdcXYc6OKGGNLUttwUUUbzHWCBLl/lahrxM47kNK4qk37hfHey/Mhajoy+UfcPQF/k15zCDL7AnY9mO7RjLnnyBGZzDr3nJAMa3CkHFk9HXBoGpA3cL8MWdOl/haXi6IW7Pod9/LjX7tUi/FEWv5c+rLG89r6ynHr30lnnt+FJNJF6izqcXxSU1mYb0NdHlDXcObQgAiihWGN/7r3E3d3M3d3Ev17N1Qg7P/lUAV/Nx6dMxxt2q2urXodwTuEdY60csf3YImI4IKsXsHPrTYoVqIoE+cTcTxBjdV51CJcliO4FtJKNpaWABIKiEq3NkRF92n9x87duQgfko7jKB3T1lgd02+zcsM/tMY0kiCGxLfzKpsmQz2jaomf8c0xJMQ5Ug4KPoZlSFTCYDBgBBdO6RIlp9fAooXhdTyW4NUG9KJln7ICtFXGX2dwKdTBQlLgN0cQLPm82kWLOqaksL/a0XOZEu0X90ZcHOPk8EBfEQDkdRGrgAOMJKslJE8aqUStmtAacArQEcJxO8MOZbl8R+rflfLPm68lJN7Gs8ZA3dT1zlyYy3bwQUD/MfAve8JIS7ONWhMKht2ikBK95ABsBXrTwXOkNHIwEQFF3KAbdHMmyE7F8cY7+OFJou55TA5LMHF7G07BagmLgBFMtuBF7hEiYZ85A+AE/nbzLiviBgp5Ca0eA8IesQAI3aAoIMGxdEqoBWYr9nTvyPGKtFwLJB7Mc5PMz7FZzNynv/AYs5nwMkHWUIp6kiU7w+vIbCfp4nW8AZA30LaCYAlBGeOeNfH6pzvRXYr3umFa37+ZJR1ELz7xZ8gdO5nkf4Bx/EDn8eq/knj3EjZ/AlPmYZhoJUU1/iAZmVYplpKIRAr6U6KhTjZBS3NDhIpM0kgD6AbiZ9OlNYFBzeHk1kf8lU7NJDf5rZksBJw8A2/G7ARxjHZKbweT7PFPZmPFswOPJMaPj6KLN52gCsWhzBoybxhGb/f8kIPixpZJ0EqEkN/K5h8zd5z/zlWoZUdPUMQaAZ8B43MU3y9elbwa6yq5/49VCXFTw+gkO5iZUyG37MQlAOgSFcayZ+GTPN52cNTEPQugOA/o3V7GA0749wJHM4SYo7V/P0DUEQiNx3uZWvs5uUcSNyr5E1uQDtNoTdOYWFvGs2CD8h0CMJArAjx/NtDpdo4zywk9QPVg4Atd4FLpFtoDOSxkFD4qdVo3zCNBKh+eVN7uXHHM8UxjCSDeRGUN8EbsBIxjCF4/kxd/OPiFm4VKXcbACBa4TdduoJ7YryMZY24T6w7SRA4A2w1BzDcuQlew9sLpG3fZ3qQzNuVAEr0M0bLOEpFrOYp1jCG3THijp4sRuBapYDH8XtklIyQyd5M8Wf5vWmOIm3IQBKRm/+GXuY66gMozmDd2ry8w/ten7CLUBc9ygYO4FKmVs4kAJvM4etzYaSZ09+Yc40JQeA+iDgGyfNRVzPzTwlHr5eHY6ppcg9QOAMGjiHlhL9hdNPvic+hU8wn+u4nZcto9YAdQlbtwCwD1ulmHAuNjnsIl1Pi7GNphQ5oDoA1D2w0EzrWZnBVYtRyaS08Yz+UGpi/ESbAsCRA4AjBwBHDgCOHAAcOQA4Wh88ghyt5z6BjlrUK7jH1NdorFewoxYCQFAUYdfYywJg7NdiRlkHgH4ODl3JhwQC07iVhSxkIbdxNaPE2eGbTcuI72gdAMA3RdAziU938JcmlURxtA4AoF/ygUTD6bQJGevfcGHTEyI6avIW4KNYzpcT8gMM4wqTENUBoE0BELpkPMhZ/Lv4027OLH5i1cp17G/bLSCaI+hNCbL4tHGYdOxvcwBEs4QtiWQJc8J/vQBA8NV1kSfQUcsAYF1nC3fkAODIAcCRA4AjBwBHDgCOHAAcOQA4WlcAmGSSKzlqFdLcaBIAJrsV16I0qTkA+BTdrOI9VjlqGdLc2L2xAHhJAJBjE0ctSTnJi9ggALxA3hRwdq01WxbI82JjALCcjdwMD4C2MSv6HwD6Qng+2zOabRjtqCVpG0azAwuMr1Y/AkCZSj5r6HHUsrSmSqDOWkoA5RzABwj5FQx1aykBqlXacNRapCpwcC23AEcD3VzsAOAA4ADgAOAA4ADgAOAAUAEAx8VqdDlqH/aH1dhyle3IYyOHCUftxH7tNzC22n1OBliAosedpduQelDMt+K7KwBgJM+KPclz1DakrYPPMrI6ALRwGMENseoZjgY+FbiBTdNc5+sHtmU6s5jtqC1oFtPZ1uJuHy1TXUi4NkBbTXzN0EGuJuqsiXKOmjqDHW5Ru9ZQP7QDuZ15/DIF3cR85rFlX9roeiacYRTzmM9NqeZwHrdxQOv4Z+aAr9eok+7s3EtjS2hCjTM4u7JFb10A4AQrl3B1KuDTwzgHgBgAxtMjdQ37ph4Ux7cWAGamThmrC0I6AMQBsFPqlJvapn+CA4ADgAOAA4ADgANASwDgRAcAJwG81E7LBcY7AMQAsDOF1I73LQiA41EUKKYgfTG5vTMExQxBY+QSPs0cFlDMkJotLdL9j7G0BiPGrY7nCe22GmbwZbZopSWUATbjYA5JQYcxVcpNuBZtnRzEYSlm8FAO5kOtJkGdOF/vZzxDR2pyLbmln0G34FxzzTXXXHPNNddcc80111xzzTXXXHPNNddcc821VO3/AaWumVCGHhHyAAAAAElFTkSuQmCC
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - security
  - secrets
  - gitops
  - policy
  - credentials
  links:
  - name: Vault Config Operator
    url: https://github.com/redhat-cop/vault-config-operator
  - name: Container Image
    url: https://quay.io/redhat-cop/vault-config-operator
  maintainers:
  - email: rspazzol@redhat.com
    name: Raffaele Spazzoli
  maturity: alpha
  provider:
    name: Red Hat Community of Practice
  version: 0.1.0
