## Append samples you want in your CSV to this file as resources ##
resources:
- redhatcop_v1alpha1_kubernetesauthenginerole.yaml
- redhatcop_v1alpha1_policy.yaml
- redhatcop_v1alpha1_secretenginemount.yaml
- redhatcop_v1alpha1_databasesecretengineconfig.yaml
- redhatcop_v1alpha1_databasesecretenginerole.yaml
- redhatcop_v1alpha1_randomsecret.yaml
- redhatcop_v1alpha1_authenginemount.yaml
- redhatcop_v1alpha1_kubernetesauthengineconfig.yaml
- redhatcop_v1alpha1_vaultsecret.yaml
- redhatcop_v1alpha1_passwordpolicy.yaml
- redhatcop_v1alpha1_githubsecretengineconfig.yaml
- redhatcop_v1alpha1_githubsecretenginerole.yaml
- redhatcop_v1alpha1_rabbitmqsecretengineconfig.yaml
- redhatcop_v1alpha1_rabbitmqsecretenginerole.yaml
- redhatcop_v1alpha1_pkisecretengineconfig.yaml
- redhatcop_v1alpha1_pkisecretenginerole.yaml
- redhatcop_v1alpha1_quaysecretengineconfig.yaml
- redhatcop_v1alpha1_quaysecretenginerole.yaml
- redhatcop_v1alpha1_quaysecretenginestaticrole.yaml
- redhatcop_v1alpha1_ldapauthengineconfig.yaml
- redhatcop_v1alpha1_ldapauthenginegroup.yaml
- redhatcop_v1alpha1_kubernetessecretengineconfig.yaml
- redhatcop_v1alpha1_kubernetessecretenginerole.yaml
- redhatcop_v1alpha1_jwtoidcauthengineconfig.yaml
- redhatcop_v1alpha1_jwtoidcauthenginerole.yaml
- redhatcop_v1alpha1_databasesecretenginestaticrole.yaml
- redhatcop_v1alpha1_group.yaml
- redhatcop_v1alpha1_groupalias.yaml
- redhatcop_v1alpha1_azureauthengineconfig.yaml
- redhatcop_v1alpha1_azureauthenginerole.yaml
- redhatcop_v1alpha1_gcpauthengineconfig.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
