apiVersion: redhatcop.redhat.io/v1alpha1
kind: AuditRequestHeader
metadata:
  labels:
    app.kubernetes.io/name: auditrequestheader
    app.kubernetes.io/instance: auditrequestheader-sample
    app.kubernetes.io/part-of: vault-config-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vault-config-operator
  name: auditrequestheader-sample
spec:
  authentication: 
    path: kubernetes
    role: policy-admin
  name: custom-header
  hmac: true
