apiVersion: redhatcop.redhat.io/v1alpha1
kind: Audit
metadata:
  labels:
    app.kubernetes.io/name: audit
    app.kubernetes.io/instance: audit-sample
    app.kubernetes.io/part-of: vault-config-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vault-config-operator
  name: audit-sample
spec:
  authentication: 
    path: kubernetes
    role: policy-admin
  path: audit-sample
  type: file
  options:
    file_path: stdout
    hmac_accessor: "false"
    enable_list_responses: "true"
