apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: randomsecret-password
spec:
  authentication: 
    path: kubernetes
    role: secret-writer
  path: test-vault-config-operator/kv
  secretKey: password
  secretFormat:
    passwordPolicyName: simple-password-policy
